cd C:\Windows\
@echo off
cls

// %RANDOM%- <- Insert your brand or leave it blank
// Example %RANDOM%-LEPROXY

AMIDEWINx64.EXE /IVN %RANDOM%
AMIDEWINx64.EXE /IV %RANDOM%
AMIDEWINx64.EXE /IV %RANDOM%
AMIDEWINx64.EXE /SM %RANDOM%
AMIDEWINx64.EXE /SP %RANDOM%
AMIDEWINx64.EXE /SV %RANDOM%
AMIDEWINx64.EXE /SS %RANDOM%
AMIDEWINx64.EXE /SU AUTO
AMIDEWINx64.EXE /SK %RANDOM%
AMIDEWINx64.EXE /SF %RANDOM%
AMIDEWINx64.EXE /BM %RANDOM%
AMIDEWINx64.EXE /BP %RANDOM%
AMIDEWINx64.EXE /BV %RANDOM%
AMIDEWINx64.EXE /BS %RANDOM%
AMIDEWINx64.EXE /BT %RANDOM%
AMIDEWINx64.EXE /BLC %RANDOM%
AMIDEWINx64.EXE /CM %RANDOM%
AMIDEWINx64.EXE /CV %RANDOM%
AMIDEWINx64.EXE /CS %RANDOM%
AMIDEWINx64.EXE /CA %RANDOM%
AMIDEWINx64.EXE /CSK %RANDOM%
AMIDEWINx64.EXE /PSN %RANDOM%
AMIDEWINx64.EXE /PAT %RANDOM%
AMIDEWINx64.EXE /PPN %RANDOM%
AMIDEWINx64.EXE /OS 1 %RANDOM%
AMIDEWINx64.EXE /OS 2 %RANDOM%
AMIDEWINx64.EXE /OS 3 %RANDOM%
AMIDEWINx64.EXE /OS 4 %RANDOM%
AMIDEWINx64.EXE /OS 5 %RANDOM%
AMIDEWINx64.EXE /OS 6 %RANDOM%
AMIDEWINx64.EXE /OS 7 %RANDOM%
AMIDEWINx64.EXE /OS 8 %RANDOM%
AMIDEWINx64.EXE /OS 9 %RANDOM%
AMIDEWINx64.EXE /OS 10 %RANDOM%
AMIDEWINx64.EXE /OS 11 %RANDOM%

cls
net stop winmgmt
// Network Reset ^^
