cd C:\Windows\
@echo off
cls

AMIDEWINx64.EXE /IVN %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /IV %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /IV %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /SM %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /SP %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /SV %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /SS %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /SU AUTO
AMIDEWINx64.EXE /SK %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /SF %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /BM %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /BP %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /BV %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /BS %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /BT %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /BLC %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /CM %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /CV %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /CS %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /CA %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /CSK %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /PSN %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /PAT %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /PPN %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 1 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 2 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 3 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 4 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 5 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 6 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 7 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 8 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 9 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 10 %RANDOM%-SugarDaddy
AMIDEWINx64.EXE /OS 11 %RANDOM%-SugarDaddy

cls
net stop winmgmt
